// Regenerate the sample report from the synthetic fixture article.
// Usage: npm run sample
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { fullReport } from "../src/checks/fullReport.js";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const html = readFileSync(join(root, "test", "fixtures", "bad-article.html"), "utf8");

const report = fullReport(html, "espresso descaling");

mkdirSync(join(root, "samples"), { recursive: true });
writeFileSync(join(root, "samples", "sample-report.json"), JSON.stringify(report, null, 2));

const sevIcon = { high: "[HIGH]", medium: "[MED]", low: "[LOW]" };
const lines = [];
lines.push("# Editorial QA report (sample)");
lines.push("");
lines.push("Input: the synthetic fixture article at `test/fixtures/bad-article.html`, focus keyword \"espresso descaling\".");
lines.push("This file is generated by `npm run sample`. Every number below is reproducible from the fixture.");
lines.push("");
lines.push(`**Verdict: ${report.summary.verdict}**`);
lines.push("");
lines.push(`Findings: ${report.summary.findings} (high ${report.summary.bySeverity.high} / medium ${report.summary.bySeverity.medium} / low ${report.summary.bySeverity.low})`);
lines.push("");
lines.push("| # | Severity | Finding | The fix |");
lines.push("|---|---|---|---|");
report.findings.forEach((f, i) => {
  const clean = (s) => (s ? String(s).replace(/\|/g, "\\|") : "");
  lines.push(`| ${i + 1} | ${sevIcon[f.severity]} | ${clean(f.finding)} | ${clean(f.fix)} |`);
});
lines.push("");
lines.push("## Metrics");
lines.push("");
lines.push("```json");
lines.push(JSON.stringify(report.metrics, null, 2));
lines.push("```");
writeFileSync(join(root, "samples", "sample-report.md"), lines.join("\n"));

console.log(`Wrote samples/sample-report.{json,md}: ${report.summary.findings} findings, verdict "${report.summary.verdict}"`);
